### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by casualshammy** [casualshammy/NameplateCooldowns#1]
[MaiRukki](https://wow.curseforge.com/members/MaiRukki) wrote:  
Can you add more customization such as font color, icon spacing or icon growth direction (horizontal or vertical).  
Maybe make it on par with Nameplateauras.

**Comment by randomnf** [comment]
1. Can u add toggling spells to show by click in the spell list?
Its annoying that if i need to disable some spell from tracking i need to go inside that spell and disable it there.

2. Also it would be useful to add "toggle all" option.

**Comment by casualshammy** [comment]
> 1. Can u add toggling spells to show by click in the spell list?
>    Its annoying that if i need to disable some spell from tracking i need to go inside that spell and disable it there.
> 2. Also it would be useful to add "toggle all" option.

I'll try to make this changes during this weekend. Thank you.

**Comment by casualshammy** [comment]
> 1. Can u add toggling spells to show by click in the spell list?
>    Its annoying that if i need to disable some spell from tracking i need to go inside that spell and disable it there.
> 2. Also it would be useful to add "toggle all" option.

Implemented in 80200.0-release

**Comment by casualshammy** [comment]
TODOs
<del>1. Font color</del>
2. Icon spacing
3. Icon growth direction (horizontal or vertical).

**Comment by casualshammy** [comment]
Finally, after almost 2 years, Implemented in 80300.3-release
