### ISSUE TITLE
No picture for trinket after wotlk update + missing spells

### ISSUE THREAD

**Issue by piddi19900** [casualshammy/NameplateCooldowns#104]
Hi,

Trinket is shown as a green empty square instead of the right trinket picture. A lot of spells are missing which where there before the update.

**Comment by piddi19900** [comment]
Hi, everything works, thanks man. Do you also overwork warriors?

**Comment by casualshammy** [comment]
Finally all spells are reviewed. I’m sorry this took so long.

**Comment by piddi19900** [comment]
Perfect, thank you so much, no problem

**Comment by hkipel** [comment]
Hello, is there a way to get this to track Penance CD for priests? I tried adding it to the default spells file but it does not work. I did the same to track Paladin Holy shock and that works. Not sure whats up.
