### ISSUE TITLE
I'm playing Lv60 Classic. What version should I download?

### ISSUE THREAD

**Issue by hoshihh** [casualshammy/NameplateCooldowns#105]
I have tried 80200.1, 80205.1 and 80300.7 but none of them worked.
Nothing happened even if I input /nc.

I have also tried 20501.12 which seems to be functioning but it shows nothing on enemy's nameplate.

So what version should I use?

**Comment by casualshammy** [comment]
The latest version for WoW Classic pre-TBC is [90002.1-release](https://github.com/casualshammy/NameplateCooldowns/releases/tag/90002.1-release)
If it is not working... well, pre-TBC support is dropped, I guess. Sorry. I barely have time even for working on Classic WotLK version...
