### ISSUE TITLE
MY UI KEEPS DISAPPEARING 

### ISSUE THREAD

**Issue by kung1991** [casualshammy/NameplateCooldowns#109]
Whenever I'm in a RBG or Arena my UI keeps disappearing and I believe its nameplatecooldowns because I turned it off on my addons and its not happening anymore

**Comment by RaggokO** [comment]
Same here.  Nameplate Cooldowns is causing the "many addon errors" message (no specific LUA errors).  After a period of time the UI will completely disappear requiring a reload.  This has only been happening to me when Nameplate Cooldowns is enabled and it has never happened while it is disabled.

It seems to be working correctly other than that.  Wonderful addon, btw.  It is kind of irreplaceable.  Nothing else provides the key information this does on the nameplate.

**Comment by casualshammy** [comment]
I need a bit more information, because I haven't any errors during bg (I did BfW just now). If you getting "many addon errors" message then you *have* lua errors. Try using `/console scriptErrors 1` command, I hope it still works.
Also, https://us.forums.blizzard.com/en/wow/t/ui-randomly-disappearing/1385122
![image](https://user-images.githubusercontent.com/4965168/200074536-64d63b0f-e58b-4684-8043-1933671ebc24.png)

**Comment by RaggokO** [comment]
Hope this helps.  Video has the following.

1.  Confirmation that Nameplate Cooldowns is enabled and the only addon enabled.
2.  Test Mode will reproduce this error 100% of the time (but, this is what happens in BGs as well)
3.  I must have had LUA error messages disabled.  I turn it back on with your suggestion.
4.  Reproduce the error again using Test Mode, this time with LUA error.

I tried to copy/paste the LUA error, but can't seem to get it to work.  CTRLC->CTRLV

https://www.youtube.com/watch?v=IUhOx6MCNro

**Comment by RaggokO** [comment]
The Test Mode post below this one has the copy/pasted LUA error that is seen here.

**Comment by casualshammy** [comment]
Thank you @RaggokO! I have found the bug, version with fix [100000.1-release](https://github.com/casualshammy/NameplateCooldowns/releases/tag/100000.1-release) is available for download.

**Comment by RaggokO** [comment]
Cool!  Downloaded update.  Test Mode working and did a full BG with no issues.   :)

Thanks for this extremely useful addon.
