### ISSUE TITLE
Solo Shuffle does not reset CDs

### ISSUE THREAD

**Issue by Maximos7** [casualshammy/NameplateCooldowns#115]
**Describe the bug**
When in solo shuffle after 1st round the icons keep showing on players like they are on cd.
Smtg needs to be done cause this is a major flaw :/ Thnak you!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by vendethiel** [comment]
FWIW the event I use is PVP_MATCH_ACTIVE

**Comment by Maximos7** [comment]
> FWIW the event I use is PVP_MATCH_ACTIVE

What do you mean? Whats FWIW?

**Comment by casualshammy** [comment]
Thank you @vendethiel. This issue is fixed in `100002.1-release`
