### ISSUE TITLE
All Evoker spells not showing

### ISSUE THREAD

**Issue by Rainnydusk** [casualshammy/NameplateCooldowns#117]
**Describe the bug**
There are no spells under the "Evoker" tab. All other classes are working fine. Thanks for creating this great Addon!

**Expected behavior**

**Screenshots**

![dsfde](https://user-images.githubusercontent.com/119632475/205166013-c208289b-5ffb-4c99-b5a7-71da76b41a35.PNG)

**Comment by casualshammy** [comment]
Hello! Please try the latest release `100002.2-release`

**Comment by Rainnydusk** [comment]
It's working beautifully now. Thank you soooo much. This is a wonderful addon for pvp players!
