### ISSUE TITLE
Addon not workin

### ISSUE THREAD

**Issue by Guitarshot** [casualshammy/NameplateCooldowns#12]
Hey i tried disabling everything, redownloading, since around november/december nothing works, tought i'd open a ticket since i've seen streamers still using it. Any other possible fix? I use base ui with big bars...

**Comment by casualshammy** [comment]
Hi. Do you play classic or retail WoW?
Try to delete NameplateAuras settings file.

**Comment by Guitarshot** [comment]
Hey thanks for quick answer

> Hi. Do you play classic or retail WoW?
> Try to delete NameplateAuras settings file.

I play retail and used to play in classic a bit. Not sure if it works in classic right now. Is nameplate auras another addon? I don't have that, but i've deleted from retail>interface>addon folder nameplate cooldowns and also tried with twitch uninstall. I also notice that the spells names are in italian tough i'm playing the english version of the game even when i reinstall or try older versions of the addon. I'm mostly testing in arena since i don't have anyone to do so in duels atm.

**Comment by casualshammy** [comment]
> Is nameplate auras another addon?

My bad. Please delete **World of Warcraft\\__retail__\WTF\Account\#######\SavedVariables\NameplateCooldowns.lua**

> I also notice that the spells names are in italian tough i'm playing the english version of the game even when i reinstall or try older versions of the addon.
That's very strange. I don't know how you could get such error...

**Comment by Guitarshot** [comment]
Doing that worked! It changed the names of spells to english. Tough it isn't tracking avenging wrath for some reason, maybe some others too dunno. I switched the game language some time ago but was still working so idk. But thanks!!

**Comment by Guitarshot** [comment]
ah maybe he was playin crusader talent, does that change the name?

**Comment by Guitarshot** [comment]
now dueled a holy, holy paladin wings don't show, but when he swapped ret avenging wrath showed so idk. Maybe vision of perfection bugs it
