### ISSUE TITLE
Update for Wotlk 3.4.1 pls : ))

### ISSUE THREAD

**Issue by Detonite** [casualshammy/NameplateCooldowns#123]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by piddi19900** [comment]
I got this error 315x:

315x ...aceNameplateCooldowns/libs/LibButtonGlow.lua:71: bad argument #1 to 'SetTarget' (Usage: local success = self:SetTarget(target))
[string "=[C]"]: in function `SetTarget'
[string "@NameplateCooldowns/libs/LibButtonGlow.lua"]:71: in function <...aceNameplateCooldowns/libs/LibButtonGlow.lua:69>
[string "@NameplateCooldowns/libs/LibButtonGlow.lua"]:180: in function <...aceNameplateCooldowns/libs/LibButtonGlow.lua:127>
[string "@NameplateCooldowns/libs/LibButtonGlow.lua"]:211: in function <...aceNameplateCooldowns/libs/LibButtonGlow.lua:208>
[string "@NameplateCooldowns/libs/LibButtonGlow.lua"]:232: in function <...aceNameplateCooldowns/libs/LibButtonGlow.lua:216>
[string "@NameplateCooldowns/NameplateCooldowns.lua"]:529: in function <...aceNameplateCooldowns/NameplateCooldowns.lua:529>

Locals:
(*temporary) = Alpha {
 0 = <userdata>
}
(*temporary) = "NAurasButtonGlowOverlay1Spark"

**Comment by piddi19900** [comment]
Hope this is because of the version :)

**Comment by casualshammy** [comment]
Thanks for reporting! Please try the latest wotlk release (30401.0-release)
