### ISSUE TITLE
Add Spells to Track in WotLK Classic

### ISSUE THREAD

**Issue by Colerain** [casualshammy/NameplateCooldowns#124]
Is adding spells to track and assigning a cooldown only available in the Retail version of WoW? I don't see a way to change the list other than to enable/disable and change the cooldown on already tracked spells.

**Comment by casualshammy** [comment]
Unfortunately, it is not possible to add spells either in retail version nor in classic version. I have described why [here](https://github.com/casualshammy/NameplateCooldowns/issues/121#issuecomment-1373631830)
