### ISSUE TITLE
Deathknight's pet spell "Gnaw" not included in trackable spells

### ISSUE THREAD

**Issue by brutalglad** [casualshammy/NameplateCooldowns#127]
Deathknight ghouls have a pet ability called "Gnaw" that stuns the target for 3sec. It is a impactful ability, much like the Warlock Felhunter's pet ability Spell Lock. 

I was wondering if you could add this ability to the list of trackable abilities. Thanks!

https://www.wowhead.com/wotlk/spell=47481/gnaw

**Comment by brutalglad** [comment]
This is for the WOTLK addon

Sorry for not mentioning this in my original post

**Comment by casualshammy** [comment]
Sorry for late reply.
Implemented in `30401.1-release`

**Comment by brutalglad** [comment]
Thank you :D
