### ISSUE TITLE
Please add Holy Shock spell (Paladin) to be tracked

### ISSUE THREAD

**Issue by Speedfiremvp** [casualshammy/NameplateCooldowns#128]
Arena players need to track Holy Shock on the enemy paladins, this is super important for pvp in wotlk.
Please add the option of tracking Holy shock, or even better, an option to manually add spells by the spell ID + manual CD

Tyvm

**Comment by casualshammy** [comment]
Sorry for late reply.
Implemented in `30401.1-release`

**Comment by Speedfiremvp** [comment]
> Sorry for late reply. Implemented in `30401.1-release`

POG thanks man!
