### ISSUE TITLE
Druid: mangle, thrash missing

### ISSUE THREAD

**Issue by Gerchan** [casualshammy/NameplateCooldowns#129]
I can't find Mangle and Thrash abilities in the spell list, kinda important ones I think, any way to add them? Thanks! :)

**Comment by casualshammy** [comment]
Hello,
I guess it's about DF. I'm not doing PvP now, but... isn't Mangle a powerful, but just damaging spell with relatively short cooldown?
Thrash doesn't have a cooldown at all, isn't it?

**Comment by Gerchan** [comment]
Both thrash and mangle have cooldown, it's just that I find myself constantly looking at action bar to see whether those spells are off CD since you use them all the time, I would rather look at the actual game :D
