### ISSUE TITLE
Add on not working 

### ISSUE THREAD

**Issue by beedracass** [casualshammy/NameplateCooldowns#13]
Hello
I would really like to use this add-on, I’ve heard great things! I have downloaded and installed it but it does not show up as an add-on in World of Warcraft. When I type /NC I get an error code. Will it work with legion ? I don’t have BFA yet. It says it supports classic, is it only for classic ? I’m just trying to figure out if I’m doing something wrong. All of my other add-ons seem to be functioning fine.

 Thanks so much for your help.
Bridgette

**Comment by casualshammy** [comment]
Hello.
Where you've downloaded NC?
What version of WoW are you using? It is displayed on login screen.

**Comment by beedracass** [comment]
Thanks for the response. I got it from curseforge,  I’m using 8.3 I think... it’s the most recent version but I only have Legion so far. I’ll be getting BFA this week. No it doesn’t show on login screen. I installed it the same way I installed my other addons so I’m kind of confused. I appreciate your help! 

Thanks!
Bridgette

**Comment by casualshammy** [comment]
Could you please make a zip archive of 'NameplateCooldowns' folder which placed in your 'World of Warcraft\_retail_\Interface\AddOns' folder? Upload this archive here, please.
Also, what locale are you playing with?

**Comment by Diablolock** [comment]
I can tell something is not working indeed. The spell list is not showing completely. I can't see all the spells avaiable.
