### ISSUE TITLE
Hunter Dissengage is not tracked.

### ISSUE THREAD

**Issue by Speedfiremvp** [casualshammy/NameplateCooldowns#132]
Request to add the spell Disengage - Hunter to the tracked enemy CDS
https://www.wowhead.com/wotlk/spell=781/disengage

CD: 25s
Talent "Survival Tactics" reduces the cd in 4s
Glyph Of Disengage Reduces the cooldown in 5s

Normally hunters have 16s CD on Disengage in arena, where is actually useful to track the cd.

Thank you very much for your time and work man <3

**Comment by casualshammy** [comment]
Thank you for such detailed request, I appreciate it.
Added to spell list in version `30401.3-release`
