### ISSUE TITLE
Visibility of CDs on diff zones

### ISSUE THREAD

**Issue by Diablolock** [casualshammy/NameplateCooldowns#135]
Hi, would like to request an option to set the visibility of the cooldowns in Epics BGs (Ashran, AV, IoC, WG) just as like we have on your other addon, NameplateAuas.

e/ It says 40man bg but Ashran for example is a 35man BG so I'm not sure if this filter still works there.

![Captura de tela 2023-09-04 122133](https://github.com/casualshammy/NameplateCooldowns/assets/41457628/d2192312-b820-4ba8-9ecb-cefb6d5f6279)

**Comment by casualshammy** [comment]
Hi,
Added in `100107.0-release`. I hope it works because I didn't have chance to play epic bg :)

**Comment by Diablolock** [comment]
Just tested it on Wintergrasp it the filter doesn't work.

**Comment by casualshammy** [comment]
> Just tested it on Wintergrasp it the filter doesn't work.

Please try the latest version (`100107.3-release`)
