### ISSUE TITLE
Every new character should default to "Default" profile instead of creating a new profile for them

### ISSUE THREAD

**Issue by ghost** [casualshammy/NameplateCooldowns#138]
It is incredibly annoying to have to swap profiles whenever logging on a new character that hasn't been logged on while NameplateCooldowns has been installed. Most of us use the same profile so it kind of feels pointless to outright create a new profile every time a new character is encountered.

It would be better if addon didn't create a new profile for every new character and instead just defaulted to "Default", users can create a new profile for the character if they want to.

**Comment by casualshammy** [comment]
Hello,
I don't think the most of players create characters so often. Current behavior is default for Ace3Profile-based addons so I don't think it's necessary to change it.
