### ISSUE TITLE
Having cooldowns showing at all times

### ISSUE THREAD

**Issue by faal1** [casualshammy/NameplateCooldowns#14]
Hello! 

I started using this addon and I really love it, one thing I wanted to ask, 

is it possible to have the cooldowns show up at all times? I have certain spells selected only and I would love to have them show up at all times so I would know what the opponent has up. a similar option is there for omnibar but I prefer this addon over it and if the option is there I can just remove omnibar.

Thank you!

**Comment by casualshammy** [comment]
Hello. Sorry for the late reply.
I was asked about it before, but I don't understand the purpose of such feature. If you're playing pvp (and even have selected only most important cooldowns), you're already know what cooldowns your opponent can use. Also, addons can't determine specialization of enemy player exactly and instantly (I'm talking about open world pvp), so you'll constantly get a panel with a lot of spells that your opponet will not be able to use.

**Comment by faal1** [comment]
The feature is useful in Arena I use the same on omnibar, is that a feature you can add easily maybe?

**Comment by vendethiel** [comment]
plz dont use stalebots
