### ISSUE TITLE
Nameplate cooldowns for upcoming spells. + Inverse. 

### ISSUE THREAD

**Issue by Madsvittrup** [casualshammy/NameplateCooldowns#141]
Hi! I made an altered version of your addon for personal use that tells me when an ability is about to come off cooldown in a certain time (4 seconds). I use this on all DPS classes. Very useful to know what's about to happen.

On healer classes I use the unaltered version but reversed. I was wondering if it was possible to implement these two so that one can use both at the same time? So I can both see when the enemy is ready to use a certain spell, and when it's about to come off CD within the next 4 seconds (Or some set time)

Either way your addon is awesome. Thanks for all the hard work, appreciate it.

**Comment by Madsvittrup** [comment]
Basically I want the inverse setting but where I can also see abilities right before they come off CD. (Maybe as a seperate line of icons)

**Comment by casualshammy** [comment]
Hi!
Sorry for the late reply. You can get a sort of desired behavior if you enable both `Inverse logic` and `Show inactive cooldowns` options, plus newly-implemented time filter should be set to 4 sec. You'll see spells that enemy can use in color and spells that enemy can't use right now in grayscale.
![image](https://github.com/casualshammy/NameplateCooldowns/assets/4965168/f44da4ce-1663-4b94-b752-0e8b13451a22)
![image](https://github.com/casualshammy/NameplateCooldowns/assets/4965168/0263b23b-03c5-4322-915b-4f76db22d30b)
