### ISSUE TITLE
Heroic leap

### ISSUE THREAD

**Issue by DragonTheta** [casualshammy/NameplateCooldowns#142]
Hi, I noticed that heroic leap is not showing up above my opponent's name plate even when they use it. So far I have tested it for warrior and the other warrior abilities are working great. How can I get heroic leap to display? Thank you.

**Comment by casualshammy** [comment]
Hi!
Classic or DF?

**Comment by DragonTheta** [comment]
It's DF. Thank you

**Comment by casualshammy** [comment]
I've added missing spell id in version `100205.5-release`. Thank you for reporting!
