### ISSUE TITLE
Lua Error while trying to change text color.

### ISSUE THREAD

**Issue by yigitkahraman** [casualshammy/NameplateCooldowns#143]
10.2.6 was same with 10.2.5.

When you click on Text/Text Color you get Lua Error below:  (reloading UI doesnt fix it)

Message: ...erface/AddOns/NameplateCooldowns/src/options-gui.lua:677: attempt to call method 'SetColorRGB' (a nil value)
Time: Wed Mar 20 22:24:40 2024
Count: 3
Stack: ...erface/AddOns/NameplateCooldowns/src/options-gui.lua:677: attempt to call method 'SetColorRGB' (a nil value)
[string "@Interface/AddOns/NameplateCooldowns/src/options-gui.lua"]:677: in function <...erface/AddOns/NameplateCooldowns/src/options-gui.lua:663>

Locals: callback = <function> defined @Interface/AddOns/NameplateCooldowns/src/options-gui.lua:665
(*temporary) = nil
(*temporary) = ColorPickerFrame {
 0 = <userdata>
 GetColorRGB = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:79
 DragBar = Frame {
 }
 OnKeyDown = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:53
 cancelFunc = <function> defined @Interface/AddOns/NameplateCooldowns/src/options-gui.lua:665
 SetupColorPickerAndShow = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:62
 OnLoad = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:3
 func = <function> defined @Interface/AddOns/NameplateCooldowns/src/options-gui.lua:665
 GetPreviousValues = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:91
 GetColorAlpha = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:83
 GetExtraInfo = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:87
 Header = Frame {
 }
 Footer = Frame {
 }
 OnShow = <function> defined @Interface/FrameXML/ColorPickerFrame.lua:34
 Border = Frame {
 }
 Content = Frame {
 }
 opacityFunc = <function> defined @Interface/AddOns/NameplateCooldowns/src/options-gui.lua:665
}
(*temporary) = 0.700000
(*temporary) = 1
(*temporary) = 0
(*temporary) = "attempt to call method 'SetColorRGB' (a nil value)"
addonTable = <table> {
 coroutine_delete = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:118
 INSTANCE_TYPE_SCENARIO = "scenario"
 msg = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:46
 BuildCooldownValues = <function> defined @Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua:179
 ICON_GROW_DIRECTION_DOWN = "down"
 deepcopy = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:16
 GetDefaultDBEntryForSpell = <function> defined @Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua:74
 SORT_MODE_INTERRUPT_OTHER = "interrupt-other"
 colorize_text = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:34
 coroutine_queue = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:107
 INSTANCE_TYPE_ARENA = "arena"
 ICON_GROW_DIRECTION_LEFT = "left"
 TestModeActive = true
 SORT_MODE_NONE = "none"
 EPIC_BG_ZONE_IDS = <table> {
 }
 OnDbChanged = <function> defined @Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua:258
 ImportNewSpells = <function> defined @Interface/AddOns/NameplateCooldowns/src/database.lua:56
 DisableTestMode = <function> defined =[C]:-1
 AllCooldowns = <table> {
 }
 INSTANCE_TYPE_PVP = "pvp"
 ShowGUI = <function> defined @Interface/AddOns/NameplateCooldowns/src/options-gui.lua:1772
 HUNTER_FEIGN_DEATH = 5384
 MigrateDB = <function> defined @Interface/AddOns/NameplateCooldowns/src/database.lua:48
 ALL_CLASSES = "ALL-CLASSES"
 SORT_MODE_TRINKET_OTHER = "trinket-other"
 Print = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:8
 SetCooldownTooltip = <function> defined @Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua:277
 msgWithQuestion = <function> defined @Interface/AddOns/NameplateCooldowns/src/utilities.lua:62
 SPELL_PVPTRINKET = 336126
 GuiOnDbReload = <function> defined @Interface/AddOns/NameplateCooldowns/src/options-gui.lua:1764
 Interrupts = <table> {
 }
 db = <table> {
 }
 INSTANCE_TYPE_PARTY = "party"
 GLOW_TIME_INFINITE = 4000000000
 INSTANCE_TYPE_RAID = "raid"
 Trinkets = <table> {
 }
 UNKNOWN_CLASS = "MISC"
 SPELL_PVPADAPTATION = 195901
 ICON_GROW_DIRECTION_UP = "up"
 CDs = <table> {
 }
 SpellNameByID = <table> {
 }
 SpellT

**Comment by casualshammy** [comment]
Hello,
Sorry for the late reply. Thank you for the report, this bug is fixed in version `100206.0-release`
