### ISSUE TITLE
Is there an update for Cata? :)

### ISSUE THREAD

**Issue by piddi19900** [casualshammy/NameplateCooldowns#147]
**WoW version**
Cataclysm

**Comment by casualshammy** [comment]
Not currently, but I'll do my best to review all this cds faster...

**Comment by Mhortai** [comment]
I use this addon in all versions of the game. Can't wait for the Cata classic update! Thanks for all your hard work!

**Comment by danlvn-gitlub** [comment]
about as much as 50k players used this addon constantly on wotlk classic. I wish my skills were that useful in life for the others as yours.

**Comment by casualshammy** [comment]
Cata version is available on Curseforge and Wago.
All bug reports are highly appreciated.
