### ISSUE TITLE
inverse logic cata

### ISSUE THREAD

**Issue by chipotleandchill** [casualshammy/NameplateCooldowns#148]
CATA

im using this addon to show enemy kicks/silences. inverse logic doesn't seem to always be working. not sure if the enemy has to use the kick/interrupt for it to trigger but it seems to not work right away. i fight a warrior who has pummel up and it isn't showing. I fight a paladin who has rebuke up and it isn't showing. then randomly it seems to work great

**Comment by casualshammy** [comment]
Hello,
If enemy hasn't used spell, its icon will not be shown. Is this your case?

**Comment by chipotleandchill** [comment]
Yes
