### ISSUE TITLE
Nameplatecooldown doesn’t work

### ISSUE THREAD

**Issue by Vore21** [casualshammy/NameplateCooldowns#150]
**WoW version**
Retail

**Describe the bug**
Hello first thing excuse my english. So i’ve used nameplatecooldown for years and i can’t play without it 
So how did the problem happen? I made a shaman and when I queued for arena i noticed there is something off about the game I couldn’t see any cooldowns above the enemy player so i tried to switch the addon off and on and still there is no cooldowns to be tracked , then i loged to my main character and i dueled someone and it worked i could see the enemy cooldown above the nameplate so what i did that i deleted the addon and redownloaded it again and now it doesn’t work for any of my characters used older versions of the addon and still it doesn’t work , so what i did that i uninstalled wow and reinstalled it again and still it doesn’t work and went to Warcraft\retail\WTF\Account#######\SavedVariables\NameplateCooldowns.lua

and deleted it and still the addon doesn’t seem to work even in wow chat when i type /nc nothing show up i’ve tried everything nothing seems to work even went to in game options then addons then played with the addon settings and profiles nothing worked all of my addons work perfectly only nameplatecooldown
And btw when i log into wow it says that nameplatcooldown is out of date i went to curse forge i saw that I’ve downloaded the latest version which is 10.2.7

**Comment by Vore21** [comment]
Also when i log in it says in the chat 
Nameplatecooldowns: Converting DB up to version 0
Nameplatecooldowns: Converting DB up to version 1
Nameplatecooldowns: Converting DB up to version 2
Nameplatecooldowns: Converting DB up to version 3
Nameplatecooldowns: Converting DB up to version 4
Nameplatecooldowns: Converting DB up to version 5
Nameplatecooldowns: Converting DB up to version 6
Nameplatecooldowns: Converting DB up to version 7

**Comment by Vore21** [comment]
Message: ...ace/AddOns/NameplateCooldowns/NameplateCooldowns.lua:187: attempt to call global 'GetSpellLink' (a nil value)
Time: Sat Jul 27 19:56:01 2024
Count: 1
Stack: ...ace/AddOns/NameplateCooldowns/NameplateCooldowns.lua:187: attempt to call global 'GetSpellLink' (a nil value)
[string "@Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua"]:187: in function BuildCooldownValues'
[string "@Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua"]:210: in function <...ace/AddOns/NameplateCooldowns/NameplateCooldowns.lua:207>
[string "@Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua"]:882: in function ?'
[string "@Interface/AddOns/NameplateCooldowns/NameplateCooldowns.lua"]:777: in function <...ace/AddOns/NameplateCooldowns/NameplateCooldowns.lua:777>

Locals: (for state) = <table> {
 HUNTER = <table> {
 }
 MISC = <table> {
 }
 PALADIN = <table> {
 }
 MAGE = <table> {
 }
 EVOKER = <table> {
 }
 PRIEST = <table> {
 }
 SHAMAN = <table> {
 }
 WARRIOR = <table> {
 }
 WARLOCK = <table> {
 }
 DEMONHUNTER = <table> {
 }
 ROGUE = <table> {
 }
 DRUID = <table> {
 }
 MONK = <table> {
 }
 DEATHKNIGHT = <table> {
 }
}
(for control) = "HUNTER"
class = "HUNTER"
cds = <table> {
 199483 = 60
 359844 = 180
 1543 = 20
 375891 = 45
 212638 = 25
 19574 = 90
 187707 = 15
 187650 = 23
 264735 = 137.400000
 186387 = 30
 212431 = 30
 109304 = 120
 190925 = 30
 205691 = 120
 109248 = 45
 213691 = 30
 53480 = 60
 781 = 20
 19577 = 60
 201430 = 120
 236776 = 37.500000
 5384 = 28
 356719 = 60
 308491 = 60
 53271 = 22.500000
 186265 = 167.400000
 288613 = 80
 147362 = 24
 186257 = 90
}
(for state) = <table> {
 199483 = 60
 359844 = 180
 1543 = 20
 375891 = 45
 212638 = 25
 19574 = 90
 187707 = 15
 187650 = 23
 264735 = 137.400000
 186387 = 30
 212431 = 30
 109304 = 120
 190925 = 30
 205691 = 120
 109248 = 45
 213691 = 30
 53480 = 60
 781 = 20
 19577 = 60
 201430 = 120
 236776 = 37.500000
 5384 = 28
 356719 = 60
 308491 = 60
 53271 = 22.500000
 186265 = 167.400000
 288613 = 80
 147362 = 24
 186257 = 90
}
(for control) = 1543
spellId = 1543
cd = 20
(temporary) = "New spell has been added: %s (%s)"
(temporary) = nil
(temporary) = 1543
(temporary) = "attempt to call global 'GetSpellLink' (a nil value)"
AllCooldowns = <table> {
 199483 = 60
 1543 = 20
 359844 = 180
}
addonTable = <table> {
 INSTANCE_TYPE_SCENARIO = "scenario"
 ICON_GROW_DIRECTION_DOWN = "down"
 SORT_MODE_INTERRUPT_OTHER = "interrupt-other"
 INSTANCE_TYPE_ARENA = "arena"
 ICON_GROW_DIRECTION_LEFT = "left"
 SORT_MODE_NONE = "none"
 EPIC_BG_ZONE_IDS = <table> {
 }
 AllCooldowns = <table> {
 }
 INSTANCE_TYPE_PVP = "pvp"
 HUNTER_FEIGN_DEATH = 5384
 ALL_CLASSES = "ALL-CLASSES"
 SORT_MODE_TRINKET_OTHER = "trinket-other"
 SPELL_PVPTRINKET = 336126
 Interrupts = <table> {
 }
 db = <table> {
 }
 INSTANCE_TYPE_PARTY = "party"
 GLOW_TIME_INFINITE = 4000000000
 INSTANCE_TYPE_RAID = "raid"
 Trinkets = <table> {
 }
 UNKNOWN_CLASS = "MISC"
 SPELL_PVPADAPTATION = 195901
 ICON_GROW_DIRECTION_UP = "up"
 CDs = <table> {
 }
 SpellNameByID = <table> {
 }
 SpellTextureByID = <table> {
 }
 Reductions = <table> {
 }
 ICON_GROW_DIRECTION_RIGHT = "right"
 INSTANCE_TYPE_PVP_BG_40PPL = "pvp_bg_40ppl"
 INSTANCE_TYPE_NONE = "none"
 SORT_MODE_INTERRUPT_TRINKET_OTHER = "interrupt-trinket-other"
 INSTANCE_TYPE_UNKNOWN = "unknown"
 SORT_MODE_TRINKET_INTERRUPT_OTHER = "trinket-interrupt-other"
}
SpellNameByID = <table> {
 199483 = "Camouflage"
 1543 = "Flare"
 359844 = "Call of the Wild"
}
db = <table> {
 ShowCooldownsOnCurrentTargetOnly = false
 TimerTextXOffset = 0
 IconSize = 26
 ShowOldBlizzardBorderAroundIcons = false
 TimerTextUseRelativeScale = true
 EnabledZoneTypes = <table> {
 }
 DBVersion = 0
 ShowBorderInterrupts = true
 IgnoreNameplateScale = false
 TimerTextSize = 13
 ShowInactiveCD = false
 IconSortMode = "none"
 SpellCDs = <table> {
 }
 MigrationVersion = 8
 IconXOffset = 0
 BorderInterruptsColor = <table> {
 }
 BorderTrinketsColor = <table> {
 }
 TimerTextAnchor = "CENTER"
 CDFrameAncho

**Comment by Vore21** [comment]
Message: ...erface/AddOns/NameplateCooldowns/src/options-gui.lua:1347: attempt to concatenate field '?' (a nil value)
Time: Sat Jul 27 20:10:05 2024
Count: 7
Stack: ...erface/AddOns/NameplateCooldowns/src/options-gui.lua:1347: attempt to concatenate field '?' (a nil value)
[string "@Interface/AddOns/NameplateCooldowns/src/options-gui.lua"]:1347: in function <...erface/AddOns/NameplateCooldowns/src/options-gui.lua:1344>

Locals: self = Button {
 Disabled = Texture {
 }
 Border = Texture {
 }
 Background = Texture {
 }
 Icon = Texture {
 }
 Normal = Texture {
 }
 closeButton = Button {
 }
 font = "Fonts\FRIZQT__.TTF"
 fontSize = 11.999999
 fontFlags = ""
 Text = FontString {
 }
 CheckBox = CheckButton {
 }
 Highlight = Texture {
 }
 grayed = false
}
(*temporary) = GameTooltip {
 ItemTooltip = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 numMoneyFrames = 1
 supportsItemComparison = true
 supportsDataRefresh = true
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 shoppingTooltips = <table> {
 }
 updateTooltipTimer = 0.057000
 TextRight1 = GameTooltipTextRight1 {
 }
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
(*temporary) = "NC CD: "
(*temporary) = nil
(*temporary) = 2094
(*temporary) = "attempt to concatenate field '?' (a nil value)"
spellID = 2094
addonTable = <table> {
 INSTANCE_TYPE_SCENARIO = "scenario"
 ICON_GROW_DIRECTION_DOWN = "down"
 SORT_MODE_INTERRUPT_OTHER = "interrupt-other"
 INSTANCE_TYPE_ARENA = "arena"
 ICON_GROW_DIRECTION_LEFT = "left"
 TestModeActive = false
 SORT_MODE_NONE = "none"
 EPIC_BG_ZONE_IDS = <table> {
 }
 AllCooldowns = <table> {
 }
 INSTANCE_TYPE_PVP = "pvp"
 HUNTER_FEIGN_DEATH = 5384
 ALL_CLASSES = "ALL-CLASSES"
 SORT_MODE_TRINKET_OTHER = "trinket-other"
 SPELL_PVPTRINKET = 336126
 Interrupts = <table> {
 }
 db = <table> {
 }
 INSTANCE_TYPE_PARTY = "party"
 GLOW_TIME_INFINITE = 4000000000
 INSTANCE_TYPE_RAID = "raid"
 Trinkets = <table> {
 }
 UNKNOWN_CLASS = "MISC"
 SPELL_PVPADAPTATION = 195901
 ICON_GROW_DIRECTION_UP = "up"
 CDs = <table> {
 }
 SpellNameByID = <table> {
 }
 SpellTextureByID = <table> {
 }
 Reductions = <table> {
 }
 ICON_GROW_DIRECTION_RIGHT = "right"
 INSTANCE_TYPE_PVP_BG_40PPL = "pvp_bg_40ppl"
 INSTANCE_TYPE_NONE = "none"
 SORT_MODE_INTERRUPT_TRINKET_OTHER = "interrupt-trinket-other"
 INSTANCE_TYPE_UNKNOWN = "unknown"
 SORT_MODE_TRINKET_INTERRUPT_OTHER = "trinket-interrupt-other"
}

**Comment by casualshammy** [comment]
Hello.
I've just pushed version `110000.0-release`, please update.

**Comment by Vore21** [comment]
i love  u thank you thaaaank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
