### ISSUE TITLE
GetSpellInfo

### ISSUE THREAD

**Issue by ryulinho** [casualshammy/NameplateCooldowns#151]
**WoW version**
Retail, Classic, WotLK...

Retail 11.0.2

**Describe the bug**

2x NameplateCooldowns/src/utilities.lua:94: attempt to call upvalue 'GetSpellInfo' (a nil value)
[string "@NameplateCooldowns/src/utilities.lua"]:94: in function <NameplateCooldowns/src/utilities.lua:93>
[string "@NameplateCooldowns/NameplateCooldowns.lua"]:183: in function `BuildCooldownValues'
[string "@NameplateCooldowns/NameplateCooldowns.lua"]:210: in function <...aceNameplateCooldowns/NameplateCooldowns.lua:207>
[string "@NameplateCooldowns/NameplateCooldowns.lua"]:882: in function `?'
[string "@NameplateCooldowns/NameplateCooldowns.lua"]:777: in function <...aceNameplateCooldowns/NameplateCooldowns.lua:777>

Locals:
t = <table> {
}
key = 199483
(*temporary) = nil
(*temporary) = 199483
(*temporary) = "attempt to call upvalue 'GetSpellInfo' (a nil value)"
GetSpellInfo = nil

GetSpellInfo is deprecated; see https://warcraft.wiki.gg/wiki/API_C_SpellBook.GetSpellInfo

**Comment by BloodDragon2580** [comment]
**Change the file NameplateCooldowns/src/utilities.lua on line 94:**
`		local spellName = GetSpellInfo(key);`
**to**
`		local spellName = C_Spell.GetSpellInfo(key);`

**And on line 86:**
`		local texture = GetSpellTexture(key);`
**to**
`		local texture = C_Spell.GetSpellTexture(key);`

**Comment by casualshammy** [comment]
> **Change the file NameplateCooldowns/src/utilities.lua on line 94:** ` local spellName = GetSpellInfo(key);` **to** ` local spellName = C_Spell.GetSpellInfo(key);`
> 
> **And on line 86:** ` local texture = GetSpellTexture(key);` **to** ` local texture = C_Spell.GetSpellTexture(key);`

Don't do this, you may lose all addon settings. `C_Spell.GetSpellInfo` is not a just replacement of `GetSpellInfo`, it returns __table__

**Comment by BloodDragon2580** [comment]
On my side it works without loosing anything.

**Comment by casualshammy** [comment]
I've pushed version `110002.1-release`.

**Comment by BloodDragon2580** [comment]
> I've pushed version `110002.1-release`.

Thx
