### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Tryophelia** [casualshammy/NameplateCooldowns#153]

**Comment by Tryophelia** [comment]
![20240827_205349](https://github.com/user-attachments/assets/f694bc1c-20b5-44de-93c1-89e83284fc00)

**Comment by casualshammy** [comment]
HI,
Is there any lua error? I cannot repro this bug rigth now...

**Comment by Tryophelia** [comment]
Hey, no errors at all... Anyway I can force Lua errors?

1. Install/uninstalled curse multiple times, including wtf folder/add-on folder
2. Deactivated all other add-ons except this one

Still the same...

**Comment by casualshammy** [comment]
> Anyway I can force Lua errors?

You can enable them using this command: `/console scriptErrors 1`. Then, try to hover the cooldown icon. Something will happen :)

You can disable lua errors with this command: `/console scriptErrors 0`

**Comment by Tryophelia** [comment]
Hey thanks, I got the lua error with your command

"Message: ...downs/libs/LibRedDropdown-1.0/LibRedDropdown-1.0.lua:328: attempt to call global 'GetSpellTexture' (a nil value)
Time: Fri Aug 30 21:07:55 2024
Count: 1
Stack: ...downs/libs/LibRedDropdown-1.0/LibRedDropdown-1.0.lua:328: attempt to call global 'GetSpellTexture' (a nil value)
[string "@Interface/AddOns/NameplateCooldowns/libs/LibRedDropdown-1.0/LibRedDropdown-1.0.lua"]:328: in function <...downs/libs/LibRedDropdown-1.0/LibRedDropdown-1.0.lua:325>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>

Locals: spellName = "Asphyxiate"
spellDesc = "Lifts the enemy target off the ground, crushing their throat with dark energy and stunning them for 4 sec."
(*temporary) = nil
(*temporary) = 108194
(*temporary) = "attempt to call global 'GetSpellTexture' (a nil value)"
spell = <table> {
 spellID = 108194
}
spellID = 108194
self = Frame {
 icon = Texture {
 }
 text = FontString {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}"

**Comment by casualshammy** [comment]
Thank you for reporting!
Please check out the latest version `110002.2-release`.

**Comment by Tryophelia** [comment]
yes, its fixed! thanks so much for the fast turn around!
