### ISSUE TITLE
Cant figure out nameplate misalignment issue

### ISSUE THREAD

**Issue by rbgdevx** [casualshammy/NameplateCooldowns#155]
**WoW version**
Retail

**Describe the feature you'd like to be implemented**
I currently have a weakaura where i align icons to the to nameplates and i noticed it aligns directly to the healthbar, so if i do "LEFT" and "RIGHT" respectively the icon starts immediately where the healthbar ends. However if i choose those same settings with NameplateCooldowns it always has a gap and never actually starts where the healthbar begins or ends and can't figure out why or how anchoring works exactly to get it to match

Like ideally without having to do X and or Y offsets my thought is it should align to the nameplate (healthbar) exactly but it never does and just curious whats going on, for context im a developer. i know you're using the nameplate as the anchor so maybe nameplate is more than just the healthbar or something? not sure.

Examples:
![Screenshot 2024-10-02 004616](https://github.com/user-attachments/assets/2c4c3576-938c-4739-b03f-8442729660c7)
![Screenshot 2024-10-02 004546](https://github.com/user-attachments/assets/9aca1f2b-6e13-47ca-afa8-09777b48a96c)

**Comment by rbgdevx** [comment]
Update: I did figure out what i was looking for and it appears that WeakAuras does indeed attach to 
```
frame.UnitFrame.healthbar
```
which is why the alignment hugs the bar itself.

**Comment by casualshammy** [comment]
Hello,
You're right - nameplate frame is bigger than actually visible health bar. Unfortunately many of nameplate addons 1) aggressively modify (resize, move) nameplate's internal frames and 2) addon's healthbar size is different from Blizz' internal healthbar. Thus there isn't reliable way to attach icons to healthbar.

For example, I use ThreatPlates addon. My another addon NameplateAuras supports attachment directly to Blizz' healthbars, but I had to implement a workaround for ThreatPlates.
Attachment to nameplate frame:
![image](https://github.com/user-attachments/assets/29030a63-6081-4df2-b2cc-a2156d38324b)
Attachment to healthbar:
![image](https://github.com/user-attachments/assets/ea07b4e8-6bbe-455b-8e02-1479dd39a563)
Attachment to TP healthbar (correct):
![image](https://github.com/user-attachments/assets/83137013-2e18-41ed-b17f-3e98cae37906)

**Comment by rbgdevx** [comment]
that makes sense! thank you for the thorough explanation!
