### ISSUE TITLE
New spell Icon

### ISSUE THREAD

**Issue by Chevaliere** [casualshammy/NameplateCooldowns#17]
Hello, when I add a new spell (evasion, shadow reflector trinket, free action potion,...) with the spell ID, how can I have the game icon showing up? Instead of the face icon.
Thanks in advance

**Comment by casualshammy** [comment]
Hello.
Sorry, it is how WoW API works. Addon don't have an idea about trinkets and potions, it just receives icon for spell id. I can add icons manually, if you want, but I need list of wowhead links :D
