### ISSUE TITLE
Missing Version tag in toc file

### ISSUE THREAD

**Issue by casperstorm** [casualshammy/NameplateCooldowns#23]
Hello,

I am currently creating a [Addon Manager](https://github.com/casperstorm/ajour/) and while parsing the `.toc` files I've noticed that NameplateCooldowns does not contain any `## Version` tag: https://github.com/casualshammy/NameplateCooldowns/blob/master/NameplateCooldowns.toc.

I rely on the local files in order to know name, version etc. So without a version tag i can't show NameplateCooldowns in the application. Is there a reason for not including a version tag?

**Comment by casualshammy** [comment]
Hello.
I forgot about this tag :) I've pushed new TOC file. Thank you!
BTW, I look forward to use your manager, it looks simple and clean.

**Comment by casperstorm** [comment]
Woah, and already live:
<img width="899" alt="Screenshot 2020-08-31 at 20 08 03" src="https://user-images.githubusercontent.com/2248455/91751882-c25a3d80-ebc5-11ea-8859-f0270a195d5d.png">

Thank you so much for the quick response.
