### ISSUE TITLE
Rework spell handling

### ISSUE THREAD

**Issue by casualshammy** [casualshammy/NameplateCooldowns#25]
Spell handling is quite old, most part of the code is legacy from Icicle.
Make it more organized:
  - make 'charactersDB' to contain unit GUIDs instead of names;
  - spell entry in 'charactersDB' must NOT contain 'expires' field. We can't update nameplates if spell entry in db is changed. Replace this field with smth like 'timeOfCast';
  - fix sorting functions. It's just ugly;

**Comment by Diablolock** [comment]
Would it be possible to separate spell by class/type? I remember back in time it used to be like that.

e.g.:
1) Class
1.1) CD
1.2) CC
1.3) Interrupt

It would make our life easier when setting a profile.

Thx in advance.

**Comment by Diablolock** [comment]
Hey Shammy in addition, if you ever want to improve the spell handling I found these guides on wowhead that have all the CDs/CC/Immunities/Interrupt and a lot more. This could be useful for NamePlateAuras as well.

1) https://www.wowhead.com/guides/class-utility-overview-battle-for-azeroth#personals-damage-mitigation
 
2) https://www.wowhead.com/crowd-control-diminishing-returns-wow-pvp
