### ISSUE TITLE
Option to hide CDs on Personal Resource Bar

### ISSUE THREAD

**Issue by BoscoDomingo** [casualshammy/NameplateCooldowns#28]
Since my own abilities are already in my bars, I know what my CDs are. I don't need the extra icons next to my Personal Resource Bars. Being able to hide them would be very nice, and I think simple

**Comment by BoscoDomingo** [comment]
![WoWScrnShot_091920_202555](https://user-images.githubusercontent.com/46006784/93686412-5bd68a00-fab6-11ea-9093-700ab882f519.jpg)

You can clearly see here that the CDs are behind my WeakAuras due to them being attached to my PRB. It's information I already have and thus don't really need. Thanks!

**Comment by casualshammy** [comment]
Thank you for reporting! Obviously you don't want to see your own cooldowns on personal nameplate. I just forgot about this nameplate. This issue is fixed in 80300.10.1-release (will be available in Twitch client soon).

**Comment by BoscoDomingo** [comment]
Wonderful news! Thanks for such a swift response and fix. Congrats on such a simple yet brilliant addon!
