### ISSUE TITLE
Addon stopped working on Russian localization

### ISSUE THREAD

**Issue by stoonya** [casualshammy/NameplateCooldowns#30]
It works fine while I am using English, but when I switch to Russian, the icons are not shown above the nameplates. I can still open the settings, everything works fine except showing the cooldowns above the nameplate. 

P.S.: To change the game language, go to settings in battle net and select "Game settings"

**Comment by casualshammy** [comment]
Hello.
Unfortunately it's not a bug. For performance reasons spell names in database are localized. You have to create a new profile in NameplateCooldowns if you switch to another locale.

**Comment by stoonya** [comment]
Hey, thank you for your reply! Addon reinstallation helped. I know it's a corner case, but maybe it would worth adding this info to the addon description (up to you). Just FYI, I think all similar addons work this way, OmniBar, also didn't work.
