### ISSUE TITLE
Any chance to get single target option back?

### ISSUE THREAD

**Issue by rezwalker** [casualshammy/NameplateCooldowns#33]
It never really worked properly in the past, and now I see it's gone. Is it because it's not possible? I love the addon but it would often look like a huge mess when I'm facing many enemies (in Battlegrounds for instance).

**Comment by casualshammy** [comment]
Quite offensive. This option is in `Filters` category of options UI. I'm not usually using this feature, but in test mode it works as intended.

**Comment by rezwalker** [comment]
How is this offensive? I'm trying to help you with your mod and I'm letting you know the feature does not work well. Else what is the point of posting here?

**Comment by casualshammy** [comment]
Okay, maybe I have chosen incorrect words and you wasn't offensive. But for me,
> It never really worked properly in the past
doesn't seem like bug report or feature request. Can you please explain, what is wrong with this feature?
