### ISSUE TITLE
Spells and Icon Rows

### ISSUE THREAD

**Issue by Johaylon** [casualshammy/NameplateCooldowns#34]
Hello. The two things I'm going to say are not really issues, but some quality of life improvements for you to work on if you have free time. 

1)Its great that I can choose which spells to show or not, however, could you add a class filter on it? 

For example, I see an icon which I dont know on a mage and I want to learn what it is and remove it or keep it in the spells list. Instead of going through all the spells in the spells section or googling mage abilities on the internet, this class filter would help a lot.

2)Sometimes players have too much cooldown on them that it really starts getting too long in one line. Could you add a couple of options so we can choose how many rows/columns we can have?

For example, lets say my spells on a nameplate go like 1-2-3-4-5-6-7-8 and keep adding up. 

I'd prefer if we could choose to make it like this 1-2-3-4.....or.....1-2-3-4-5.....or......1-2-3
..................................................................................................5-6-7-8..............6-7-8-9-10 .......... 4-5-6
................................................................................................................................................................. 7-8-9

Adding dots so the placement of the numbers wont get changed upon posting. You know what I mean. Again, these arent issues, but a couple of quaility of life suggestions. Thanks for the wonderful addons and have fun! :)

Edit: Sorry, my first suggestion has already been suggested by someone else. I wasnt sure wether to keep it or remove it from my post.

**Comment by casualshammy** [comment]
Hello. Thank for suggestions!
I think I'll return class filter during November.
About multiple rows... I was asked about this in the past. I'm not sure I'll implement it, but I'll consider it once more.

**Comment by Johaylon** [comment]
Thank you :)

**Comment by casualshammy** [comment]
Class filter is implemented in the latest beta (you can install it via Twitch client or download [directly](https://github.com/casualshammy/NameplateCooldowns/releases/download/90001.2-beta/NameplateCooldowns-90001.2-beta.zip)).

**Comment by Johaylon** [comment]
Thank you :)
