### ISSUE TITLE
Cooldowns are moving randomly

### ISSUE THREAD

**Issue by HuMa69** [casualshammy/NameplateCooldowns#38]
If you move the CDs from his default position after a while they move randomly below their fixed position, for example i move the CDs close to the nameplate without a empty space then after a while they move under the nameplate bar, i tried with empty wow install and with no addons only Neatplates and nameplatecooldowns, also tried with "ignore nameplate scale" but its just the same
This bug only happens in the last version 90001.1, the 90001.0 version have not this bug, seems like in the last version the CDs doesnt keep their fixed position and they eventually move theirselves a bit below the position you want

**Comment by casualshammy** [comment]
Hello.
> This bug only happens in the last version 90001.1, the 90001.0 version have not this bug

There are not changes between `90001.0` and `90001.1`. `90001.1` is just a [localization fix](https://github.com/casualshammy/NameplateCooldowns/compare/90001.0-release...90001.1-release). Could you please post a screenshot with disposition of nameplate and NC's icons? And another screenshot with disposition of nameplate and icons when they're moved?
