### ISSUE TITLE
Cooldowns overlapping character due to Personal Resource Display

### ISSUE THREAD

**Issue by z-waters** [casualshammy/NameplateCooldowns#41]
**Describe the bug**
I am unsure why the cooldowns meant to be above enemy nameplates are stacking above my character's Personal Resource Display bar, making them cover my character model.

**To Reproduce**
1. Have Personal Resource Display enabled
2. Use addon

**Expected behavior**
I would expect the cooldowns only to be above enemy nameplates. Perhaps it is interpreting the default Personal Resource Display bar as another nameplate?

**Screenshots**

![nameplate_error](https://user-images.githubusercontent.com/64579582/100020251-5fc3a880-2d94-11eb-9f98-415dbd868598.png)

**Comment by casualshammy** [comment]
Hello.
Are cooldowns always shown above personal resource bar, or just if test mode of NC is enabled?

**Comment by z-waters** [comment]
I feel silly for posting it. It was only the test mode.

**Comment by casualshammy** [comment]
It's not silly. I'll make cooldowns not display on personal bar, even in test mode. Thank you.
