### ISSUE TITLE
Spell duration before cooldown

### ISSUE THREAD

**Issue by GJordao** [casualshammy/NameplateCooldowns#42]
It would be great if the addon could display the spell duration before displaying the cooldown.

So for example. if a Druid uses Survival Instincts it would be cool if the spell icon could show 6 seconds of duration and when the spell ends show the remaining cooldown (3 minutes - 6 seconds). The active duration could be shown with a glowing border, or different text color to differentiate from the cooldown

Cheers

**Comment by casualshammy** [comment]
Sorry, currently I have not plans on implementing such feature.

**Comment by vendethiel** [comment]
fwiw, LibCooldownTracker provides such info
