### ISSUE TITLE
Cannot open spell list

### ISSUE THREAD

**Issue by fisken1991** [casualshammy/NameplateCooldowns#45]
9x ...aceNameplateCooldowns\NameplateCooldowns-90002.0-release.lua:694: bad argument #1 to 'next' (table expected, got nil)
[string "=[C]"]: in function `next'
[string "@NameplateCooldowns\NameplateCooldowns-90002.0-release.lua"]:694: in function <...aceNameplateCooldowns\NameplateCooldowns.lua:688>
[string "@NameplateCooldowns\NameplateCooldowns-90002.0-release.lua"]:2124: in function <...aceNameplateCooldowns\NameplateCooldowns.lua:2120>
[string "@NameplateCooldowns\NameplateCooldowns-90002.0-release.lua"]:2172: in function <...aceNameplateCooldowns\NameplateCooldowns.lua:2171>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by casualshammy** [comment]
Possibly fixed in 90002.1-release
