### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Reineke123** [casualshammy/NameplateCooldowns#46]
**Describe the bug**
The cooldowns are not visible. It is the only addon I have activated. If I go into the options and enable test mode they show up and if I right click on my target there comes a lua error. 

Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
Time: Sun Jan  3 17:03:41 2021
Count: 1
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 totalAbsorb = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 0 = <userdata>
 background = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 totalAbsorbOverlay = <unnamed> {
 }
}

**Comment by Epsynus** [comment]
I get 3 different LUA errors with this addon, only got this addon enabled and still get them.

They seem to only trigger for me if I got "Personal Resource Display" ticked in Interface -> Names.

and since I do. Well it gets cumbersome with these errors.

Here's a pastebin link of all 3 errors, instead of cluttering this comment further.

[LUA Errors](https://pastebin.com/TdjMxeg6)
