### ISSUE TITLE
Cooldown swirl on icons

### ISSUE THREAD

**Issue by eycaluton** [casualshammy/NameplateCooldowns#47]
Hello! Would it be possible for you to add an option to display the cooldown swipe on icons? I have tried to pair the addon with OmniCC  to achieve this effect, but I can't seem to make it work.

Thank you for this wonderful addon :)

**Comment by Rackelhardt** [comment]
yeah would be awesome actually

**Comment by eycaluton** [comment]
Hello! Any updates on this? An alternative idea that might be easier to implement would be to have the text change colour as it's approaching the end (such as red text with 5 seconds remaining for example) This would make it easier to see at a glance, making snap decisions a lot easier.

Again I'd like to reiterate that the addon is fantastic, and I appreciate the work you put into maintaining it

**Comment by casualshammy** [comment]
This feature will be implemented in the next week.

**Comment by casualshammy** [comment]
This feature is implemented in version `90105.18-beta`. Unfortunately, I had not much time to test it, so I cannot push it in the release branch.
![image](https://user-images.githubusercontent.com/4965168/156935413-8a77761c-e598-4f50-a39c-79c91728a7f9.png)

**Comment by eycaluton** [comment]
Wonderful! I have tested it over a few games and it works great for the most part. The only thing I have noticed is that it does not work if you have "Inverse Logic" checked. Not sure if that is intentional or not
