### ISSUE TITLE
Cooldowns overlapping with the HP Bar

### ISSUE THREAD

**Issue by ultrascris06** [casualshammy/NameplateCooldowns#48]
hey, I have an issue with nameplatecooldowns, whenever someone uses too many cds they keep going over the HP BAR instead of staying on the right side  https://gyazo.com/a3a1c39100a9762aa48c88656ee67de2 how can I solve this issue?

Settings
Anchor point: Top right
Anchor point(to parent): Right
Icongrowth direction: Left/Right - same thing happens

What I want is to have the CDs start from the right side of the nameplate and keep going to the right(or go right then below).
Is there any way to solve this?

**Comment by casualshammy** [comment]
Hi,
Try 
```
Anchor point: Left
Anchor point(to parent): Center
Icongrowth direction: Right
```

**Comment by ultrascris06** [comment]
That worked, thank you very much!
