### ISSUE TITLE
Not able to select cooldowns for classes

### ISSUE THREAD

**Issue by NicksCodingHub** [casualshammy/NameplateCooldowns#51]
When I open the spell selection window, there are only 5 spells (insignia, asphyxiate, ...) in the "all" tab. As soon as I switch to a class like "rogue", there is nothing to select. Even if I add for example evasion manually, it doesn't pop up for rogue.

What can I do here? I would love to use this addon but it seems completely broken for me.

**Comment by casualshammy** [comment]
Do you have any lua errors? If not, could you please post the file located in `<<World of Warcraft folder>>\_retail_\WTF\Account\<<account number>>\SavedVariables\NameplateCooldowns.lua`?

**Comment by ztnko** [comment]
when i first time launch addon i had same problem. but then i make new profile and all spell appears as intended.
