### ISSUE TITLE
not working with plater

### ISSUE THREAD

**Issue by ztnko** [casualshammy/NameplateCooldowns#53]
NameplateCooldowns works fine if i turn off Plater addon.
with plater addon on it also don't give a single lua error. more then that - test button correctly shows test icons on nameplate but on arena it don't show anything.

**Comment by ztnko** [comment]
i don't know how it works but when i install another addon - nameplateauras - nameplatecooldowns start working with plater...
so now i just turn off everything in nameplateauras and use it to just make nameplatecooldowns working

**Comment by ztnko** [comment]
wrong info... :(
it works only once and then again - NameplateCooldowns stop show anything

**Comment by casualshammy** [comment]
This bug occurs only on arenas? Maybe you have disabled NC for arenas? There is the option in 'Filters' tab in options window.

**Comment by ztnko** [comment]
if it is the case then it would not work when i turn off plater.

**Comment by casualshammy** [comment]
This bug occurs only on arenas?
I've installed [Plater Nameplates](https://www.curseforge.com/wow/addons/plater-nameplates) addon and then I have done 1 epic bg. NC is properly working.

**Comment by ztnko** [comment]
i make another testings. turn on NameplateCooldowns. check that test work fine on covenant dolls. while doing all these preparation bugsack+buggrabber catch these errors:

```
1x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.999998
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0.999998
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}
```

after that i join bg. don't see any cooldowns on nameplates like it was on arenas.
i check filters. everything checked https://puu.sh/Hci3r/f1577dab7a.png
https://puu.sh/Hci3C/bdab83543f.png

then i turn off plater and nc start working as intended https://puu.sh/Hci4h/7b27fc4e6b.jpg
then i turn on plater during bg and it's working https://puu.sh/Hci5p/604eeebce3.jpg
and it continue to  work whole bg
before and during 2nd bg there was 2 errors
```
1x [ADDON_ACTION_BLOCKED] Модификация 'NameplateCooldowns' пыталась вызвать защищенную функцию 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:244>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:181: in function `OnTargetChanged'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:61: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>
```
but it don't affect anything - addon still working
https://puu.sh/Hci9B/1f1062f604.jpg

i use this plater profile https://wago.io/tj_AiUBPd

**Comment by casualshammy** [comment]
Hmm. I'll continue to use Plater, maybe I'll be lucky enough to catch this bug.

**Comment by casualshammy** [comment]
So far 3 weeks without errors. Sorry, I'll uninstall Plater now, because problem is seems to be somewhere else.
