### ISSUE TITLE
With update, all the spells I added have been removed. Is there a way to know which spells I did add before this update removed them?

### ISSUE THREAD

**Issue by Jdekk** [casualshammy/NameplateCooldowns#55]
They tracked flawlessly, so it's incredibly frustrating to have them removed and have my ability to add them removed.  I have to go through all spells in the game again to make sure I don't miss one of those, unless there is a way to tell which spells I had tracking before this update.

I want to suggest to you to add the ability to track all of them, but I can't do so if I no longer have access to my list of spells.

**Comment by casualshammy** [comment]
I'm so sorry, but unfortunately, I had to do this downgrade. With user-defined spells it was hard to provide updated cooldowns (there were merge conflicts). BTW I've tried to add all important spells on the start of Shadowlands, so maybe you'll find it sufficient.
If you have not backups, but you added your spells by spell id then they still in database. File located in `<<World of Warcraft folder>>\_retail_\WTF\Account\<<account number>>\SavedVariables\NameplateCooldowns.lua`. There will be text like 
``` lua
NameplateCooldownsAceDB = {
	["profileKeys"] = {
		_<profile keys>_
	},
	["profiles"] = {
		[_<profile name>_] = {
			...
			["SpellCDs"] = {
				[47585] = {
					["enabled"] = true,
				},
				[207777] = {
					["enabled"] = true,
				},
				[18499] = {
					["enabled"] = true,
				},
```
Numbers in square brackets are spell ids. There will be spells added by you **and also default spells**, so it would be hard to differentiate them. Sorry again.

**Comment by Jdekk** [comment]
Thanks for the answer.  I've given up on knowing what I used to track and perhaps there are more that should be added, but I just skimmed the talent calculators on Wowhead and I would like these 27 cooldowns to be added if possible:

**Death Knight:** 1. Abomination Limb (covenant); 2. Wraith Walk

**Demon Hunter:** 1. The Hunt (covenant); 2. Eye Beam

**Druid:** 1. Convoke the Spirits (covenant); 2. Frenzied Regeneration

**Hunter:** 1. Resonating Arrow (covenant)

**Mage:** 1. Radiant Spark (covenant)

**Paladin:** 1. Ashen Hallow (covenant); 2. Shield of Vengeance

**Priest:** 1. Mindgames (covenant); 2. Mass Dispel; 3. Vampiric Embrace

**Rogue:** 1. Marked for Death; 2. Kidney Shot; 3. Gouge; 4. Between the Eyes

**Shaman:** 1. Stormkeeper; 2. Earthen Wall Totem

**Warlock:** 1. Soul Rot (covenant); 2. Dark Soul: Misery; 3. Dark Soul: Instability; 4. Havoc

**Warrior:** 1. Spear of Bastion (covenant); 2. Rallying Cry; 3. Intervene

**Comment by casualshammy** [comment]
Thank for your contribution! Spell list is updated in version 90002.3-release.

**Comment by Jdekk** [comment]
Wow, you added all of them!  Thanks a ton; PvPers everywhere will rejoice and I get to feel cool like this is my update.  :)

**Comment by ZoopGH** [comment]
Hello, I've also ran into the problem with custom spells I used to track that are no longer there. Could you please add this when you have the chance? Thank you.

Paladin (Holy) - PvP Talent
**Divine Favor**
Spell ID: 210294
30 sec cooldown

https://www.wowhead.com/spell=210294/divine-favor

**Comment by casualshammy** [comment]
@ZoopGH Thank you for detailed description! Added in 90002.4-release.

**Comment by Resune** [comment]
You've forgotten to add a lot of the covenant abilities, I'd also like to ask why you don't let us change the cooldown of the spells already available?
