### ISSUE TITLE
Revise all spells

### ISSUE THREAD

**Issue by azertywow** [casualshammy/NameplateCooldowns#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by casualshammy** [comment]
I cannot fix incorrect cooldown value if you didn't specify it.

**Comment by azertywow** [comment]
> I cannot fix incorrect cooldown value if you didn't specify it. Cooldown time is the minimal possible. Almost all spells could be modified by talents, pvp talents or specializations, so minimal value is NOT the one you see in tooltip of the spell.



> Я не могу исправить неверное значение восстановления, если вы его не указали. Время перезарядки минимально возможное. Почти все заклинания можно модифицировать с помощью талантов, pvp-талантов или специализаций, поэтому минимальное значение НЕ то, что вы видите во всплывающей подсказке к заклинанию.

the paladin does not display correctly, for example: Blessing of Sacrifice,Divine Shield,Blessing of Protection,Blessing of Freedom,Lay on Hands

**Comment by casualshammy** [comment]
Ah, you're right. Okay, I'll revise all spells in next few days.

**Comment by scorpgul** [comment]
Hi could you add Disc Priest Rapture please?

**Comment by casualshammy** [comment]
Ability to edit cooldowns are returned in the latest release.

**Comment by scorpgul** [comment]
> 
> 
> Ability to edit cooldowns are returned in the latest release.

Thanks a lot man
