### ISSUE TITLE
Blink Not Working

### ISSUE THREAD

**Issue by tokeshlol** [casualshammy/NameplateCooldowns#60]
Hello,

I noticed that the "Blink" spell is not working.  The Spell ID seems correct.. yet it definitely does not seem to appear when mages use the spell.

**Comment by casualshammy** [comment]
I have not 60 lvl mage, only 35 lvl, and Blink works fine for me, spell id is correct. I'll tr to check it on BG.

**Comment by vendethiel** [comment]
Is shimmer supported too?
