### ISSUE TITLE
Is this addon working in classic?

### ISSUE THREAD

**Issue by HuMa69** [casualshammy/NameplateCooldowns#61]
wowcurse says "Supports World of Warcraft Classic." but when im ingame /nc doesnt work and i dont see any cooldown over nameplates, this addon works on classic?

**Comment by casualshammy** [comment]
Sorry, I've forgotten to delete this line from description. Last version working on Classic is [90002.1-release](https://github.com/casualshammy/NameplateCooldowns/releases/tag/90002.1-release) (not sure because I'm not playing Classic and don't have time for it)

**Comment by HuMa69** [comment]
ah okay, but that version is working good in classic? it will keep working in tbc?

**Comment by HuMa69** [comment]
okay i tried and it gives full lua errors, so isnt working sadly :d
