### ISSUE TITLE
Warrior, Paladin spells wrong CD

### ISSUE THREAD

**Issue by scorpgul** [casualshammy/NameplateCooldowns#63]
Hi,

Warrior Die By the Sword is still the wrong 3 min CD from BFA.

Paladin spells such as Divine Shield, Avenging Wrath, Bop, Sac are still wrong CD.

Could we get a fix on those please?

Thanks

**Comment by casualshammy** [comment]
Hi,
I've revised Paladin and Warrior spells.

Divine Shield's cooldown was changed from 120 sec to 210 sec.
Avenging Wrath seems to be correct. 180 sec base cooldown - 60 sec from [level 2](https://ru.wowhead.com/spell=317872)
BOP's cooldown was changed from 225 sec to 300 sec.
Blessing of Sacrifice seems to be correct, just 120 sec base cooldown.

Die By the Sword's cooldown was changed from **120** sec to 100 sec
