### ISSUE TITLE
Why change so we cant add spells?

### ISSUE THREAD

**Issue by fisken1991** [casualshammy/NameplateCooldowns#64]
My spells adds gone. Spells that I tracked not in list.. For example weapons of order from monk etc.

**Comment by fisken1991** [comment]
Also Divine toll, i have it checked but i does not show cd on their nameplate

**Comment by casualshammy** [comment]
Hello,
I've added `Weapons of Order`, but I don't know what is wrong with `Divine Toll`. I got its spell id from [wowhead](https://www.wowhead.com/spell=304971/divine-toll).
