### ISSUE TITLE
90002.11 LUA errors

### ISSUE THREAD

**Issue by Epsynus** [casualshammy/NameplateCooldowns#66]
**Describe the bug**
I updated to the latest release and upon entering into combat I get several LUA errors. Some only appear if I got "Personal Resource Display" ticked in Interface -> Names. But one I get even without it enabled..

What happens is it also completely breaks the personal resource display so it doesn't show my HP bar properly or starts moving it around on screen.

I have tried just having NameplateCooldowns enabled, still the same result. (I chose to enable buggrabber to easier store the lua errors)

**Expected behavior**
No errors and for the Personal Resource Display to work properly. I think part of the problem is that it is hooking into the personal nameplate and trying to modify it/display cooldowns on it, when it shouldn't. (When I enable test mode it treats it as a nameplate)

**LUA errors**
```1x [ADDON_ACTION_BLOCKED] AddOn 'NameplateCooldowns' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:119: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>
```

```1x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.999998
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0.999998
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}
```

```
4x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:216: in function `OnRaidTargetUpdate'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = nil
```

```3x FrameXML\AuraUtil.lua:58: Usage: local continuationToken, slot1, slot2, ... = UnitAuraSlots("unit" [, "filter"][, maxSlots][, continuationToken])
[string "=[C]"]: in function `UnitAuraSlots'
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:597: in function `UpdateBuffs'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:209: in function `OnUnitAuraUpdate'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:65: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = nil
(*temporary) = "HELPFUL|INCLUDE_NAME_PLATE_ONLY"
(*temporary) = 32
(*temporary) = nil
```

[Here's an image of the broken personal resource bar.](https://imgur.com/a/btSV38e)

**Comment by casualshammy** [comment]
Hello,
Just tested on my prot. paladin - even with personal resource bar enabled addon works as intended. What class are you playing?

**Comment by casualshammy** [comment]
Also I'll appreciate if you post screenshot with general settings of NameplateCooldowns.

**Comment by Epsynus** [comment]
I have been able to trigger this on both my lvl 60 Shaman (Enhance) and my lvl 51 Arcane Mage that I am currently lvling.

Screenshot of the [general settings](https://imgur.com/a/iYcG1HM)

**Comment by casualshammy** [comment]
This bug occurs after entering combat always, or sometimes? I've copied your settings and fighting with dummy just now, but got no errors >_<

**Comment by Epsynus** [comment]
I would say it happens to me 9/10 times I go into combat, there has been a few times where it hasn't happened.

It is possible that it is my fault that it is happening, I will try deleting my Interface & WTF files to reset everything, reinstall just NameplateCooldowns and see if I can get it to happen again.

I will include a video as well at that point for you, Thanks for your help so far!

**Comment by casualshammy** [comment]
I have no doubt in your words, I just can't fix bug that I can't reproduce. My main is shaman, I have personal resource bar enabled, but I have never seen this error...

**Comment by vendethiel** [comment]
That looks very similar to https://www.townlong-yak.com/bugs/gXwH4P-IOFrameSelection

**Comment by casualshammy** [comment]
I still can't reproduce that bug, but **_maybe_** version 90002.12-release solves that issue.

**Comment by casualshammy** [comment]
@vendethiel Thank you for information! But unfortunately fix provided there doesn't solve that bug, so I've just removed interactions with InterfaceOptionsFrame's "Cancel" button. Please try version 90002.13-release.

**Comment by Epsynus** [comment]
Been running 90002.13-release for ~3 hours now and I have not yet encountered a single error. Seems to have solved it all! Thanks so much!
