### ISSUE TITLE
[Feature Request] Priorities or Multiple Groups/Anchors

### ISSUE THREAD

**Issue by gobacktogo** [casualshammy/NameplateCooldowns#67]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
hey, first of all: thanks for all your work, great addon!
would it be possible to either add a priority system (for example: i would always want the gladiators medallion to show up as the left most icon), or a 2nd group that we could anchor to a different position (in that case, i would show medallion and the human anti stun racial at for example the right of the nameplate, and other cooldowns below or above the nameplate)? both would be really appreciated!
anyways, thanks again!

**Comment by casualshammy** [comment]
Hi,
If you would like to have trinkets on left (or right) side, maybe you'll find sorting feature useful. You can find it on 'General' tab of settings window.

**Comment by gobacktogo** [comment]
ah my bad! thanks!
