### ISSUE TITLE
Thank you for your hard work in making this classic compatible.

### ISSUE THREAD

**Issue by Arcaidius** [casualshammy/NameplateCooldowns#7]
From my experience with your addon, its working with every spell. The only fix I see is with a number of different spells not showing the spell icon, only the cooldown number above the nameplate. Mage spells seem to all be working to the addons intended value, but classes like warrior, rogue still have problems with their spell images showing with the cool down countdown.

**Comment by Derranion** [comment]
@casualshammy Could u tell how did you fix level 1 icons? ( line of code or release link if possible pls )

 I'll help you with the rest of them.

**Comment by casualshammy** [comment]
It's not a fix, it's just a matter of CLEU (COMBAT_LOG_EVENT_UNFILTERED). I don't know what happens, but I guess that it returns some strange values for certain spells.
This is metatable that returns textureID for spell name:
https://github.com/casualshammy/NameplateCooldowns/blob/181e63d225fc82774fab3cc89c483eb974831b6d/NameplateCooldowns_Classic.lua#L36-L42
This is event handler:
https://github.com/casualshammy/NameplateCooldowns/blob/181e63d225fc82774fab3cc89c483eb974831b6d/NameplateCooldowns_Classic.lua#L1952-L1971

**Comment by Arcaidius** [comment]
@Derranion if you figure out a fix please update on this thread ty <3

**Comment by Derranion** [comment]
Don't you think that it's related to the spell ranks in classic? 

There are no ranks in actual wow.

Looks like " GetSpellTexture(key) " method gets unknown key because of this.

Not sure why it works well for " db.SpellCDs[spellName] " though.

/eventtrace helps to see spell IDs in the game.

**Comment by casualshammy** [comment]
@Derranion 
Oh. I forgot about spell ranks, but (as you've mentioned) if CombatLogGetCurrentEventInfo() returns something like "Frostbolt (Rank 3)" then 
```
local entry = db.SpellCDs[spellName]; 
if (entry and entry.enabled) then 
```
wouldn't work at all.

**Comment by Derranion** [comment]
@casualshammy 

I can't see what's inside the " db.SpellCDs " table, probably there are values for all ranks of the spells in this table.

And looks like only rank 1 spells are in the table that " GetSpellTexture " method uses.

Because GetSpellTexture(key) works for level 1 spells and doesn't work for other spells.

**Comment by casualshammy** [comment]
@Derranion 
No, i don't think so. "db.SpellCDs" is the table that contains options for all spells. It's populated on first addon usage (with predefined list of spells), and by user via options dialog. There are not spell ranks.
```
["SpellCDs"] = {
	["Grappling Hook"] = { -- spell name is a key
		["enabled"] = true, -- is spell enabled for tracking
		["refSpellID"] = 195457, -- spell id for options dialog
		["spellIDs"] = { -- list of spell ids for tracking (it can be nil, then tracking all spells with same spell name)
			[195457] = true,
		},
		["cooldown"] = 30, -- cooldown is seconds
		["texture"] = 1373906, -- texture id for options dialog
	},
	["Revival"] = {
		["enabled"] = true,
		["refSpellID"] = 115310,
		["spellIDs"] = {
			[115310] = true,
		},
		["cooldown"] = 180,
		["texture"] = 1020466,
	},
```
Anyway, I'll up my mage to level 8 (there is rank 2 frostbolt) and try to solve this issue. But I'm banned for 'suspicious economic activity' and waiting for reply from Blizz :D

**Comment by Arcaidius** [comment]
@casualshammy ty for the effort and best of luck with the ban

**Comment by casualshammy** [comment]
Okay, there are not problems with spell ranks. 'Fireblast rank 1' and 'Fireblast rank 2' have the same names in combatlog, and my code returns correct icon id for this spells. But maybe I've found the issue. The latest release (80205.1-release) will be published soon, please check it out.

**Comment by ADSGcc** [comment]
Thanks man, can’t wait to get home and try the latest release, your addons is indeed unique and currently there is no other addon that does this feature, cuz I’ve searched and searched and couldn’t find any. Also it is really needed for world pvp as well. So once again, thanks so much for the effort, I hope to see this addon fully functional ^^
