### ISSUE TITLE
Spell Request: Feign Death (hunter)

### ISSUE THREAD

**Issue by kevindeboer** [casualshammy/NameplateCooldowns#73]
Hi,

I would like to track a hunter's feign death ability, but it is not currently tracked. 

As an affliction warlock, its really annoying to see all my dots dispelled when a hunter feign deaths. Its the Craven Strategem legendary power that causes the dispel and lowers cooldown by 15s. But its already possible to set a custom cooldown value. 

Thanks!

**Comment by casualshammy** [comment]
Hi,
Implemented in 90005.0-release.
