### ISSUE TITLE
Healer Tracker Widget for Headline View

### ISSUE THREAD

**Issue by volpemauro** [casualshammy/NameplateCooldowns#77]
The headline view x and y for the healer tracker widget have no effect. Instead, the settings of the healthbar view get applied.

**Comment by casualshammy** [comment]
Sorry, are you sure you're posting issue for the right addon? NameplateCooldowns have not deal with any healer trackers.

**Comment by volpemauro** [comment]
How embarrassing sorry, you're right, concerns the threat plates addon. Btw i love NameplateCooldowns.
