### ISSUE TITLE
Display Icon only when cooldown is up

### ISSUE THREAD

**Issue by tarasgeist** [casualshammy/NameplateCooldowns#79]
Ideally there would be a way to display cooldown icon only when spell is available to be used. For example, if Leg Sweep cooldown is up then icon appears on screen, otherwise completely hidden.

Better option yet, would be ability to have the icon appear a set amount of time before spell is off cooldown (let's say I want Leg Sweep icon to appear 5 seconds before cooldown finishes).

Thank you

**Comment by casualshammy** [comment]
Hello,
Addons have no idea about talents and sometimes even about spec of enemy players, so addons can't guess what spells player is able to use. It can be implemented by some type of 'learning' (if player used spell - hmm, lets assume he can cast it with <this> minimum cooldown), but I don't think I should do such feature. BTW, you can enable the option `Show inactive cooldowns`, so you will see spells that player have used some time ago and these spells are _possibly_ not on CD.

**Comment by tarasgeist** [comment]
I think you misunderstand my ask, sorry.
I will give you an example with Kidney Shot. There are no talents to reduce cooldown of kidney shot also.
1. I want Kidneyshot icon to be displayed when the spell is available to be used, not before. Right now, the icon appears when kidney shot is used and remains while on cooldown. I want icon when spell is NOT on cooldown.
2. I want "show inactive cooldowns" to have an option to limit it to 1-5sec remaining on cooldown.

**Comment by casualshammy** [comment]
I guess I understood you correctly but my ability to explain is poor :)
NC is imprecise. All spell CDs are measured by _minimum_ cooldown, so if you see cooldown icon you can be sure your opponent can't use this spell. If there is not icon - well, maybe he have not cd on this spell, but addon can't guarantee that.
If I'll implement option you've asked, behavior will be, erm, a bit confusing. If you can see icon then your opponent can use this spell, but what if he can't? This 1-5 sec timer will be just useless, because you can't rely on this information, especially if you guess that your opponent will press the key asap (and you want to use defensive cd, for example).
Also, when you see your opponent for the first time addon just don't know what spells he can use...
Could you please explain the purpose of such feature?

**Comment by tarasgeist** [comment]
haha ok :)
Short answer - the reason for the feature is because it's more "visually clean". This way my UI would only shows stuff I care about "right now". Cooldown not being accurate is a separate issue and is not related to my ask.

Long answer - NC is already imprecise because of cooldown reducing talents. If I add Combustion to my tracked cooldowns, it will never show correct cooldown, just approximation. I understand that. There's no way to fix it, so it's essentially irrelevant to what I'm asking.
Elaborating on my kidneyshot example. Let's say we are also tracking trinket, kick, cloak, evasion, and shadow blades for the rogue. This will give me an NC frame with 6 cooldowns (icons) cluttering up my screen. It would be cleaner to only show available cooldowns instead of all cooldowns. Also knowing what opponent can use might be more actionable than knowing what he cannot use. Finally, there are a lot more cooldowns with static cd than there are cooldowns with variable cd. The addon would be accurate more often than not.

**Comment by casualshammy** [comment]
Hello again!
I've implemented this feature. Well, a sort of. I'm not playing actively now, so I've not tested it in pvp. You'll find the checkbox at the very bottom of 'General' tab of options window.

**Comment by tarasgeist** [comment]
Works great! thank you very much. I sent you a donation.
I'm sorry to hear you're  not actively playing right now. If you get a chance to work some more on this addon, an additional option attached to "show inactive cooldowns" where we can choose to show inactive cooldown based on remaining time.  So lets say I want inactive cooldown icon to appear when there's 5 seconds or less left on cooldown.
