### ISSUE TITLE
Not all CD's properly trigger a CD icon // disabling certain spells still shows an icon. 

### ISSUE THREAD

**Issue by timvbrakel** [casualshammy/NameplateCooldowns#80]
**Describe the bug**
Pummel is not properly tracked by the addon // not showing up as a Cooldown timer icon.
Barkskin is tracked whilst being disabled. 

**To Reproduce**
1. Go to enable the spell pummel for CD tracking
2. duel a warrior
3. notice no cd-icon being displayed

**Expected behavior**
Pummel CD icon displayed above the nameplate

**Screenshots**

**Comment by casualshammy** [comment]
Hello.
When you've noticed this behavior? I mean, this bug appeared after last update (yesterday) or before?

**Comment by timvbrakel** [comment]
Hi,

First off, let me say i really like your addon. Keep up the good work.

I am using the addon / the version for TBC (20501.0-release).
From the releases i cannot tell if there's a previous version.
Hope this helps.

Have a good day!



20501.0-release
--







20501.0-release
--








20501.0-release
--

**Comment by casualshammy** [comment]
Ah, TBC! I'm just started working to make addon compatible with TBC. TBH currently only hunter spells are updated for TBC. I'll update other classes in next few days.

**Comment by timvbrakel** [comment]
ok, good to hear. As well as the active development. Looking forward to the new release. If there's anything i can assist with, e.g. testing, please let me know.

**Comment by casualshammy** [comment]
I've finally updated all spells for TBC in version 20501.7-release. I'll appreciate if you'll try it.
