### ISSUE TITLE
bcc version can't track PvP trinkets

### ISSUE THREAD

**Issue by supremecwj** [casualshammy/NameplateCooldowns#82]
I changed PvP trinkets spellid of the BCC version is 42292.  but not working

**Comment by casualshammy** [comment]
Hello,
Please update to the latest version (20501.7-release).

**Comment by supremecwj** [comment]
Hi. 20501.7-release still can't track PvP trinkets.
I think it’s because the combatlog can’t be tracked PvP trinkets.
btw thank you for your work sincerely.

**Comment by casualshammy** [comment]
Do you have PvP trinket spell in addon's settings enabled? Unfortunately, I don't have high level TBC character, so I can't test addon by myself >_<.

**Comment by supremecwj** [comment]
Yes i enabled.
Another addons omnibar historical version can't track PvP trinkets neither, but latest version fix it.
I see a comment  Needed to track PvP trinkets and possibly other spells that do not show up in COMBAT_LOG_EVENT_UNFILTERED in his code.
I think it has something to do with that
