### ISSUE TITLE
(TBC) Rogue Preparation resets too many spells. Mage Cold Snap does not reset spells

### ISSUE THREAD

**Issue by KorvoKorvo** [casualshammy/NameplateCooldowns#91]
TBC VERSION

Bug:
-Rogue's Preparation skill resets too many abilities
-Mage's refresh does not reset abilities

Reproduce:
-See enemy rogue use preparation, it will reset seemingly all of their abilities, or at least it will reset more than intended
-See enemy mage use cold snap, no abilities are reset

Expected behavior:
-Rogue's Preparation should only reset the following abilities: "When activated, this ability immediately finishes the cooldown on your Evasion, Sprint, Vanish, Cold Blood, Shadowstep and Premeditation abilities." It should not reset abilities like Blind https://tbc.wowhead.com/spell=14185/preparation
-Mage Cold Snap should refresh all frost abilities such as frost nova, summon water elemental, ice block. Looking in the code it looks like it is using the spell ID for "Icy Veins" instead of "Cold Snap". In TBC, Icy Veins is the buff that temporarily increasing casting speed, while Cold Snap is the ability that resets all frost cd.

		[12472] = {	-- MAGE: Стылая кровь https://ru.tbc.wowhead.com/spell=12472
			["reduction"] = BIG_REDUCTION,
			["spells"] = allMageSpells,

I see this info in the "default-spells.lua" file. Hunter Readiness resets all abilities, rogue preparation resets specific abilities, mage cold snap resets frost abilities, but they all look like they are using the "reset all abilities" format that hunter's readiness uses

Thank you for reading and for this addon

**Comment by casualshammy** [comment]
Hello. Thank you for detailed report, I really appreciate it.
I have fixed rogue's spells and will push changes tomorrow.
I don't know much about TBC nowadays... Are _frost_ mages using any important _fire_ or _arcane_ cooldowns? I'm trying to understand, is it required to manually add all frost spells?

**Comment by KorvoKorvo** [comment]
"I don't know much about TBC nowadays... Are frost mages using any important fire or arcane cooldowns? I'm trying to understand, is it required to manually add all frost spells?"

Yes. For example, every mage has counterspell and blink (arcane spells), even if they are deep fire or deep frost mages. Having these spells get reset would be misleading. 


The spells that get reset by cold snap are:
-cone of cold (many ranks)(tracking this doesn't matter as much because it has short cd anyway, like fire blast)
-frost nova (many ranks)
-ice barrier  (many ranks)(probably only max rank matters)  https://70.wowfan.net/en/?spell=33405
-icy veins  https://70.wowfan.net/en/?spell=12472
-ice block  https://70.wowfan.net/en/?spell=45438
-summon water elemental https://70.wowfan.net/en/?spell=31687


I think resetting frost nova all ranks is important because some mages max rank and some mages downrank. Ice Barrier max rank is probably sufficient because I don't think you ever want to downrank it. These are the same ranks that show up in  \NameplateCooldowns\src\default-spells.lua


Frost Nova Rank1-5
122 
865
6131 
10230 
27088



Cheers

**Comment by casualshammy** [comment]
Again, thank you very much for this information. I've pushed the update.
