### ISSUE TITLE
Warlock spell lock

### ISSUE THREAD

**Issue by zyzz24** [casualshammy/NameplateCooldowns#92]
**Describe the bug**
When a warlock runs Grimoire of Sacrifice and sacrifices felhunter and uses interrupts  it won't track in nameplate cooldown.

**To Reproduce**
1. Need a enemy warlock to run talent Grimoire of Sacrifice
2. Then they use Grimoire of Sacrifice on fel hunter
3. and then interrupt you and and addon won't track it as a interrupt

**Expected behavior**
Should track just like spell lock, because it is spell lock but I believe the spell ID gets changed so it instead doesn't track anything

**Screenshots**

Command demon tool tip "Commands your demon to perform its most powerful ability. This spell will transform based on your active pet" Below are the spells that get replaced by command demon. I haven't tested the other ability's and if they track or not, only interested in Spell lock being tracked. I think its just a different spell ID is all.

 Summon Imp: Singe Magic
 Summon Voidwalker: Shadow Bulwark
 Summon Succubus: Whiplash
 Summon Felhunter: Spell Lock
 Summon Felguard: Pursuit

Thank you

**Comment by casualshammy** [comment]
Hello,
Thank you for report! This issue was addressed in the latest version (`90100.17-release`)
