### ISSUE TITLE
Feign Death doesnt seem to work

### ISSUE THREAD

**Issue by kevindeboer** [casualshammy/NameplateCooldowns#93]
**Describe the bug**
A while ago I requested Hunter's Feign death to be added: https://github.com/casualshammy/NameplateCooldowns/issues/73. It was added pretty much immediately (for which thanks!), however it never actually worked :(

**To Reproduce**
I have absolutely no idea why every other spell seems to work, but feign death doesnt. It works in other CD trackers like OmniBar. I checked the source code of both addons, and the spell IDs are the same. I thought maybe it messes up when used with in conjunction with Craven Strategem legendary or Survival Tactics pvp talent. I tested it against a hunter with and without legendary and pvp talents, but it didnt seem to matter, feign death never showed.

**Expected behavior**
Feign death should show like any other spell.

**Screenshots**
![FD](https://user-images.githubusercontent.com/2820719/139721377-cb15e30f-fa5d-45d9-ae17-c1d13086c6e3.png)

**Comment by casualshammy** [comment]
Hello.
This bug is fixed in `90105.4-release`
