### ISSUE TITLE
PVP trinket status shows on allies even with "show on allies" setting toggled off

### ISSUE THREAD

**Issue by dummyaccounter** [casualshammy/NameplateCooldowns#94]
**Describe the bug**
In TBC CLASSIC version, if ally uses PVP trinket, PVP trinket cooldown status will show on them, even if this setting is not on

**To Reproduce**
If nearby ally uses pvp trinket, the cooldown will show on their nameplate. I am using mostly default settings. So far I did not notice a difference despite changing settings around to isolate a specific cause

**Expected behavior**
Shouldn't show up on ally nameplate unless "show on ally" setting is enabled

**Screenshots**
PVP trinket showing on ally nearby
https://i.imgur.com/0nQuKvN.png

**Comment by casualshammy** [comment]
Fixed in `20501.12-release`
