### ISSUE TITLE
Request to click-through?

### ISSUE THREAD

**Issue by xprepaidx** [casualshammy/NameplateCooldowns#98]
Hey, love the addon! I was wondering if there is a way already, or if i can request a feature, to be able to click-through the nameplate cooldowns? It messes me up quite a bit in pvp when i click the icons on accident which i do literally all the time. Can't click-through and i dont think there is a setting for it.

Is it possible to request this feature?

**Comment by casualshammy** [comment]
Hi!
Do you have the `Show cooldown tooltip` option enabled?

**Comment by xprepaidx** [comment]
Hey!
I do have that option turned on. See below!
![image](https://user-images.githubusercontent.com/36016981/161455470-e1a8520f-a5d0-47e1-a75a-55320e88a806.png)

**Comment by xprepaidx** [comment]
Actually im just now realizing that the Show Cooldown Tooltip once checked, doesnt let us click through. Might be a simple change!

**Comment by casualshammy** [comment]
Sorry for late reply.
Yes, I'm not 100% sure, but I guess there is API limitation - enabling tooltips makes it impossible to click through icons.

**Comment by xprepaidx** [comment]
Well that's a pain. I suppose temporarily i can just leave the tooltip stuff off as i see now it lets me click-through with the tooltip turned off
